apiVersion: v1
data:
  tls.crt: {{BASE64_ENCODED_VALUE}}
  tls.key: {{BASE64_ENCODED_VALUE}}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ WORKLOAD_CLUSTER_NAME}}
  name: {{WORKLOAD_CLUSTER_NAME}}-ca
  namespace: {{VSPHERE_NAMESPACE}}
type: cluster.x-k8s.io/secret